[package]
name = "hello"
version = "0.4.1"
authors = ["bonohub13 <ken.saito.0813@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
